version: '3.8'

services:
  login-service:
    image: login:latest
    container_name: login_service
    environment:
      - SPRING_APPLICATION_NAME=login-service
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finances
      - SPRING_DATASOURCE_USERNAME=finance_user
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      - SERVER_PORT=8081
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db10
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_USER=finance_user
      - POSTGRES_PASSWORD=12345
    ports:
      - "5437:5432"
